const AMPLITUDE_EVENTS = {
  HEADER_HOME_CLICK: "HEADER_HOME_CLICK",
  HOME_PLAYLIST_CLICK: "HOME_PLAYLIST_CLICK",
  PLAYLIST_PLAY_CLICK: "PLAYLIST_PLAY_CLICK",
  PLAYLIST_TRACK_PLAY_CLICK: "PLAYLIST_TRACK_PLAY_CLICK",
  PLAYER_PLAY_CLICK: "PLAYER_PLAY_CLICK",
  PLAYER_PREVIOUS_CLICK: "PLAYER_PREVIOUS_CLICK",
  PLAYER_NEXT_CLICK: "PLAYER_NEXT_CLICK",
  PLAYER_SLIDER_CHANGE: "PLAYER_SLIDER_CHANGE",
};

export default AMPLITUDE_EVENTS;
